services:
  - type: web
    name: baccarat-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: USERNAME
        value: tiendatoce1232
      - key: PASSWORD
        value: tiendatoceee1
